#pragma once

#include "PCH.h"

namespace AllegroDotNet::Wrapper
{
	using namespace System;

	public enum class EventType : UInt32
	{
		DisplayClose = ALLEGRO_EVENT_DISPLAY_CLOSE,
		DisplayConnected = ALLEGRO_EVENT_DISPLAY_CONNECTED,
		DisplayDisconnected = ALLEGRO_EVENT_DISPLAY_DISCONNECTED,
		DisplayExpose = ALLEGRO_EVENT_DISPLAY_EXPOSE,
		DisplayFound = ALLEGRO_EVENT_DISPLAY_FOUND,
		DisplayHaltDrawing = ALLEGRO_EVENT_DISPLAY_HALT_DRAWING,
		DisplayLost = ALLEGRO_EVENT_DISPLAY_LOST,
		DisplayOrientation = ALLEGRO_EVENT_DISPLAY_ORIENTATION,
		DisplayResize = ALLEGRO_EVENT_DISPLAY_RESIZE,
		DisplayResumeDrawing = ALLEGRO_EVENT_DISPLAY_RESUME_DRAWING,
		DisplaySwitchIn = ALLEGRO_EVENT_DISPLAY_SWITCH_IN,
		DisplaySwitchOut = ALLEGRO_EVENT_DISPLAY_SWITCH_OUT,
		JoystickAxis = ALLEGRO_EVENT_JOYSTICK_AXIS,
		JoystickButtonDown = ALLEGRO_EVENT_JOYSTICK_BUTTON_DOWN,
		JoystickButtonUp = ALLEGRO_EVENT_JOYSTICK_BUTTON_UP,
		JoystickConfiguration = ALLEGRO_EVENT_JOYSTICK_CONFIGURATION,
		KeyChar = ALLEGRO_EVENT_KEY_CHAR,
		KeyDown = ALLEGRO_EVENT_KEY_DOWN,
		KeyUp = ALLEGRO_EVENT_KEY_UP,
		MouseAxes = ALLEGRO_EVENT_MOUSE_AXES,
		MouseButtonDown = ALLEGRO_EVENT_MOUSE_BUTTON_DOWN,
		MouseButtonUp = ALLEGRO_EVENT_MOUSE_BUTTON_UP,
		MouseEnterDisplay = ALLEGRO_EVENT_MOUSE_ENTER_DISPLAY,
		MouseLeaveDisplay = ALLEGRO_EVENT_MOUSE_LEAVE_DISPLAY,
		MouseWarped = ALLEGRO_EVENT_MOUSE_WARPED,
		Timer = ALLEGRO_EVENT_TIMER,
		TouchBegin = ALLEGRO_EVENT_TOUCH_BEGIN,
		TouchCancel = ALLEGRO_EVENT_TOUCH_CANCEL,
		TouchEnd = ALLEGRO_EVENT_TOUCH_END,
		TouchMove = ALLEGRO_EVENT_TOUCH_MOVE,
	};
}
