#pragma once

#include "PCH.h"

namespace AllegroDotNet::Wrapper
{
	using namespace System;

	public enum class SystemMouseCursor : Int32
	{
		AltSelect = ALLEGRO_SYSTEM_MOUSE_CURSOR_ALT_SELECT,
		Arrow = ALLEGRO_SYSTEM_MOUSE_CURSOR_ARROW,
		Busy = ALLEGRO_SYSTEM_MOUSE_CURSOR_BUSY,
		Default = ALLEGRO_SYSTEM_MOUSE_CURSOR_DEFAULT,
		Edit = ALLEGRO_SYSTEM_MOUSE_CURSOR_EDIT,
		Link = ALLEGRO_SYSTEM_MOUSE_CURSOR_LINK,
		Move = ALLEGRO_SYSTEM_MOUSE_CURSOR_MOVE,
		Precision = ALLEGRO_SYSTEM_MOUSE_CURSOR_PRECISION,
		Progress = ALLEGRO_SYSTEM_MOUSE_CURSOR_PROGRESS,
		Question = ALLEGRO_SYSTEM_MOUSE_CURSOR_QUESTION,
		ResizeE = ALLEGRO_SYSTEM_MOUSE_CURSOR_RESIZE_E,
		ResizeN = ALLEGRO_SYSTEM_MOUSE_CURSOR_RESIZE_N,
		ResizeNE = ALLEGRO_SYSTEM_MOUSE_CURSOR_RESIZE_NE,
		ResizeNW = ALLEGRO_SYSTEM_MOUSE_CURSOR_RESIZE_NW,
		ResizeS = ALLEGRO_SYSTEM_MOUSE_CURSOR_RESIZE_S,
		ResizeSE = ALLEGRO_SYSTEM_MOUSE_CURSOR_RESIZE_SE,
		ResizeSW = ALLEGRO_SYSTEM_MOUSE_CURSOR_RESIZE_SW,
		ResizeW = ALLEGRO_SYSTEM_MOUSE_CURSOR_RESIZE_W,
		Unavailable = ALLEGRO_SYSTEM_MOUSE_CURSOR_UNAVAILABLE,
	};
}
