using System.Runtime.InteropServices;
using SubC.AllegroDotNet.Enums;
using SubC.AllegroDotNet.Models;
using SubC.AllegroDotNet.Native;

namespace SubC.AllegroDotNet;

/// <summary>
/// This static class contains the Allegro 5 library methods.
/// </summary>
public static partial class Al
{
  /// <summary>
  /// Install a keyboard driver. Returns true if successful. If a driver was already installed, nothing happens and
  /// true is returned.
  /// </summary>
  /// <returns>True if successful, otherwise false.</returns>
  public static bool InstallKeyboard()
  {
    return Interop.Context.Core.AlInstallKeyboard() != 0;
  }

  /// <summary>
  /// Returns true if <see cref="InstallKeyboard"/> was called successfully.
  /// </summary>
  /// <returns>True if <see cref="InstallKeyboard"/> was called successfully, otherwise false.</returns>
  public static bool IsKeyboardInstalled()
  {
    return Interop.Context.Core.AlIsKeyboardInstalled() != 0;
  }

  /// <summary>
  /// Uninstalls the active keyboard driver, if any. This will automatically unregister the keyboard event source with
  /// any event queues. This function is automatically called when Allegro is shut down.
  /// </summary>
  public static void UninstallKeyboard()
  {
    Interop.Context.Core.AlUninstallKeyboard();
  }

  /// <summary>
  /// Save the state of the keyboard specified at the time the function is called into the structure pointed to by
  /// <paramref name="state"/>.
  /// </summary>
  /// <param name="state">The keyboard state.</param>
  public static void GetKeyboardState(AllegroKeyboardState state)
  {
    Interop.Context.Core.AlGetKeyboardState(ref state.Struct);
  }

  /// <summary>
  /// Return true if the key specified was held down in the state specified.
  /// </summary>
  /// <param name="state">The keyboard state.</param>
  /// <param name="keyCode">The key code.</param>
  /// <returns>True if the key specified was held down in the state specified, otherwise false.</returns>
  public static bool KeyDown(AllegroKeyboardState state, KeyCode keyCode)
  {
    return Interop.Context.Core.AlKeyDown(ref state.Struct, (int)keyCode);
  }

  /// <summary>
  /// Converts the given keycode to a description of the key.
  /// </summary>
  /// <param name="keyCode">The key code.</param>
  /// <returns>The description of the key.</returns>
  public static string? KeycodeToName(KeyCode keyCode)
  {
    var result = Interop.Context.Core.AlKeycodeToName((int)keyCode);
    return Marshal.PtrToStringAnsi(result);
  }

  // /// <summary>
  // /// Returns true if setting the keyboard LED indicators is available.
  // /// </summary>
  // /// <returns>True if setting the keyboard LED indicators is available.</returns>
  // public static bool CanSetKeyboardLeds()
  // {
  //   return Interop.Context.Core.AlCanSetKeyboardLeds() != 0;
  // }

  /// <summary>
  /// Overrides the state of the keyboard LED indicators. Set LEDs to a combination of the keyboard modifier flags to
  /// enable the corresponding LED indicators (<see cref="KeyMods.NumLock"/>,
  /// <see cref="KeyMods.CapsLock"/> and <see cref="KeyMods.ScrollLock"/>
  /// are supported) or to <see cref="KeyMods.Reset"/> to return to default behavior. False is returned if the
  /// current keyboard driver cannot set LED indicators.
  /// </summary>
  /// <returns>True if the LED was set, otherwise false.</returns>
  public static bool SetKeyboardLeds(KeyMods keyMods)
  {
    return Interop.Context.Core.AlSetKeyboardLeds((int)keyMods) != 0;
  }

  /// <summary>
  /// Retrieve the keyboard event source. All keyboard events are generated by this event source.
  /// Returns <c>null</c> if the keyboard subsystem was not installed.
  /// </summary>
  /// <returns>The keyboard event source on success, otherwise <c>null</c>.</returns>
  public static AllegroEventSource? GetKeyboardEventSource()
  {
    var pointer = Interop.Context.Core.AlGetKeyboardEventSource();
    return NativePointer.Create<AllegroEventSource>(pointer);
  }
}