namespace AllegroDotNet.Models
{
    /// <summary>
    /// An event queue holds events that have been generated by event sources that are registered with the queue.
    /// Events are stored in the order they are generated. Access is in a strictly FIFO (first-in-first-out) order.
    /// </summary>
    public sealed class AllegroEventQueue : NativePointerWrapper
    {
        internal AllegroEventQueue()
        {
        }
    }
}
