using SubC.AllegroDotNet.Native;
using System;

namespace SubC.AllegroDotNet.Models
{
    /// <summary>
    /// An event queue holds events that have been generated by event sources that are registered with the queue.
    /// Events are stored in the order they are generated. Access is in a strictly FIFO (first-in-first-out) order.
    /// </summary>
    public sealed class AllegroEventQueue : NativePointerWrapper, IEquatable<AllegroEventQueue>
    {
        internal AllegroEventQueue()
        {
        }

        /// <summary>
        /// Determines if two <see cref="AllegroEventQueue"/> native pointers are equal.
        /// </summary>
        /// <param name="other">The instance to compare equality.</param>
        /// <returns>True if the native pointers are equal, otherwise false.</returns>
        public bool Equals(AllegroEventQueue other)
        {
            return NativeIntPtr == other?.NativeIntPtr;
        }
    }
}
